"""empty message

Revision ID: 02af13dda617
Revises: 
Create Date: 2024-03-22 16:05:06.160584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02af13dda617'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_user')
    op.drop_table('flight')
    # ### end Alembic commands ###
